version: '3.8'

volumes:
  postgres_badge:


services:

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "7000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  postgres_badge:
      container_name: postgres_badge
      image: postgres:16
      restart: always
      environment:
        POSTGRES_USER: username
        POSTGRES_PASSWORD: password
      ports:
        - "5432:5432"
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d
        - postgres_badge:/var/lib/postgresql/data


  app:
      build:
        context: badgeKeeperTooFastTooFurious/.
        dockerfile: Dockerfile
      container_name: app
      restart: always
      ports:
        - "8080:8080"
      depends_on:
        - postgres_badge
        - kafka
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_badge/badge_keeper_vol2_db
        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  logger:
      container_name: logger
      restart: always
      build:
        context: badgeKeeperCustomer/.
        dockerfile: Dockerfile
      ports:
        - "9090:8080"
      depends_on:
        - postgres_badge
        - kafka
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_badge:5432/badge_keeper_sensor_logger
        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092